apiVersion: apps/v1
kind: Deployment
metadata:
  name: openim-push-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openim-push-server
  template:
    metadata:
      labels:
        app: openim-push-server
    spec:
      containers:
        - name: openim-push-container
          image: openim/openim-push:v3.9
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: DEPLOYMENT_TYPE
              value: "kubernetes"
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
            - name: notification-config
              mountPath: "/config/notification.yml"
              subPath: notification.yml
              readOnly: true
          ports:
            - containerPort: 10170
            - containerPort: 12170
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
        - name: notification-config
          configMap:
            name: notification-config
