apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-rpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: friend-rpc-server
  template:
    metadata:
      labels:
        app: friend-rpc-server
    spec:
      containers:
        - name: friend-rpc-server-container
          image: openim/openim-rpc-friend:v3.8.3      
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: IMENV_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: IMENV_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_openim_password
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10240
            - containerPort: 12240
      volumes:
        - name: openim-config
          configMap:
            name: openim-config