apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-rpc-server
  template:
    metadata:
      labels:
        app: auth-rpc-server
    spec:
      containers:
        - name: auth-rpc-server-container
          image: openim/openim-rpc-auth:v3.9
          imagePullPolicy: Never
          env:
            - name: DEPLOYMENT_TYPE
              value: "kubernetes"
            - name: CONFIG_PATH
              value: "/config"
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10200
            - containerPort: 12200
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
