serviceBinaries:
  openim-api: 1
  openim-crontask: 4
  openim-rpc-user: 1
  openim-msggateway: 1
  openim-push: 8
  openim-msgtransfer: 8
  openim-rpc-conversation: 1
  openim-rpc-auth: 1
  openim-rpc-group: 1
  openim-rpc-friend: 1
  openim-rpc-msg: 1
  openim-rpc-third: 1
  openim-rpc-encryption: 1
toolBinaries:
  - check-free-memory
  - check-component
  - seq
maxFileDescriptors: 10000
