---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-deployment
spec:
  selector:
    matchLabels:
      app: friend # 选择这个指定标签执行
  replicas: 1 # 运行pod数量
  template:
    metadata:
      labels:
        app: friend # 标签
    spec:
      containers:
      - name: friend
        image: openim/friend:v2.2.0
        # imagePullPolicy: Always
        ports:
        - containerPort: 10120
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: openim-config
  strategy: #更新策略
    type: RollingUpdate # 滚动更新

