annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.12.0
description: A Library Helm Chart for grouping common logic between bitnami charts.
  This chart is not deployable by itself.
home: https://bitnami.com
icon: https://bitnami.com/downloads/logos/bitnami-mark.png
keywords:
- common
- helper
- template
- function
- bitnami
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: common
sources:
- https://github.com/bitnami/charts
type: library
version: 2.12.0
