apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msg-rpc-server
  template:
    metadata:
      labels:
        app: msg-rpc-server
    spec:
      containers:
        - name: msg-rpc-server-container
          #          image: openim/openim-rpc-msg:v3.8.3
          image: openim-rpc-msg:test
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: IMENV_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-redis-secret
                  key: redis-password
            - name: IMENV_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_username
            - name: IMENV_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_password
            - name: IMENV_KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openim-kafka-secret
                  key: kafka-username
            - name: IMENV_KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-kafka-secret
                  key: kafka-password
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10280
            - containerPort: 12280
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
