rpc:
  registerIP: ''
  listenIP: 0.0.0.0
rpcPort:
  openImThirdPort: [ 10190 ]
rpcRegisterName:
  openImThirdName: Third

prometheus:
  enable: true
  grafanaUrl: http://127.0.0.1:13000/
  prometheusPort: [ 21301 ]


