rpc:
  # The IP address where this RPC service registers itself; if left blank, it defaults to the internal network IP
  registerIP:
  # IP address that the RPC service listens on; setting to 0.0.0.0 listens on both internal and external IPs. If left blank, it automatically uses the internal network IP
  listenIP: 0.0.0.0
  # autoSetPorts indicates whether to automatically set the ports
  # if you use in kubernetes, set it to false
  autoSetPorts: true
  # List of ports that the RPC service listens on; configuring multiple ports will launch multiple instances. These must match the number of configured prometheus ports
  # It will only take effect when autoSetPorts is set to false.
  ports:

ratelimiter:
  # Whether to enable rate limiting
  enable: true
  # WindowSize defines time duration per window
  window: 10s
  # BucketNum defines bucket number for each window
  bucket: 100
  # CPU threshold; valid range 0â€“1000 (1000 = 100%)
  cpuThreshold: 800

circuitBreaker:
  enable: true
  window: 3s            # Time window size (seconds)
  bucket: 10            # Number of buckets
  success: 0.6          # Success rate threshold (0.6 means 60%)
  request: 100 # Request threshold; circuit breaker evaluation occurs when reached

prometheus:
  # Enable or disable Prometheus monitoring
  enable: true
  # List of ports that Prometheus listens on; these must match the number of rpc.ports to ensure correct monitoring setup
  # It will only take effect when autoSetPorts is set to false.
  ports:

maxConcurrentWorkers: 3
#Use geTui for offline push notifications, or choose fcm or jpns; corresponding configuration settings must be specified.
enable:
getui:
  pushUrl: https://restapi.getui.com/v2/$appId
  masterSecret:
  appKey:
  intent:
  channelID:
  channelName:
fcm:
  # Prioritize using file paths. If the file path is empty, use URL
  filePath:   # File path is concatenated with the parameters passed in through - c(`mage` default pass in `config/`) and filePath.
  authURL:   #  Must start with https or http.
jpush:
  appKey:
  masterSecret:
  pushURL:
  pushIntent:

# iOS system push sound and badge count
iosPush:
  pushSound: xxx
  badgeCount: true
  production: false

fullUserCache: true
