rpc:
  # API or other RPCs can access this RPC through this IP; if left blank, the internal network IP is obtained by default
  registerIP: 
  # Listening IP; 0.0.0.0 means both internal and external IPs are listened to, if blank, the internal network IP is automatically obtained by default
  listenIP: 0.0.0.0
  # autoSetPorts indicates whether to automatically set the ports
  # if you use in kubernetes, set it to false
  autoSetPorts: true
  # List of ports that the RPC service listens on; configuring multiple ports will launch multiple instances. These must match the number of configured prometheus ports
  # It will only take effect when autoSetPorts is set to false.
  ports:

prometheus:
  # Whether to enable prometheus
  enable: true
  # Prometheus listening ports, must be consistent with the number of rpc.ports
  # It will only take effect when autoSetPorts is set to false.
  ports:

ratelimiter:
  # Whether to enable rate limiting
  enable: true
  # WindowSize defines time duration per window
  window: 10s
  # BucketNum defines bucket number for each window
  bucket: 100
  # CPU threshold; valid range 0â€“1000 (1000 = 100%)
  cpuThreshold: 800

circuitBreaker:
  enable: true
  window: 3s            # Time window size (seconds)
  bucket: 10            # Number of buckets
  success: 0.6          # Success rate threshold (0.6 means 60%)
  requestThreshold: 100 # Request threshold; circuit breaker evaluation occurs when reached