secret: openIM123
rpcRegisterName:
  user: user
  friend: friend
  msg: msg
  push: push
  messageGateway: messageGateway
  group: group
  auth: auth
  conversation: conversation
  third: third

imAdminUserID: [ imAdmin ]

# 1: For Android, iOS, Windows, Mac, and web platforms, only one instance can be online at a time
multiLogin:
  policy: 6
  maxNumOneEnd: 30
  customizeLoginNum:
    ios: 1
    android: 1
    windows: 1
    osx: 1
    web: 1
    miniWeb: 1
    linux: 1
    aPad: 1
    iPad: 1
    admin: 1
