secret: openIM123

imAdminUserID: [imAdmin]

# 1: For Android, iOS, Windows, Mac, and web platforms, only one instance can be online at a time
multiLogin:
  policy: 1
  # max num of tokens in one end
  maxNumOneEnd: 30

rpcMaxBodySize:
  requestMaxBodySize:  8388608
  responseMaxBodySize: 8388608
