etcd:
  userName:
  password:
  secret: 

mysql:
  dbMysqlUserName: root
  dbMysqlPassword: 

mongo:
  dbUserName:   root
  dbPassword: 

redis:
  dbUserName:
  dbPassWord: 

kafka:
  SASLUserName:
  SASLPassword:

credential:
  minio:
    endpoint: 
    accessKeyID: root
    secretAccessKey: 

secret: 

tokenpolicy:
  accessSecret: "open_im_server" #token生成相关 建议修改
  accessExpire: 90 #token过期时间（天） 默认即可

messageverify:
  friendVerify: false #发送消息是否验证好友关系 false表示不验证好友关系

push:
  getui:
    pushUrl: "https://restapi.getui.com/v2/$appId"
    masterSecret: ""  #需添加
    appKey: ""  #需添加
    enable: false  #true启动个推推送

