---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-cms-deployment
spec:
  selector:
    matchLabels:
      app: admin-cms # 选择这个指定标签执行
  replicas: 2 # 运行pod数量
  template:
    metadata:
      labels:
        app: admin-cms # 标签
    spec:
      containers:
        - name: admin-cms
          image: openim/admin_cms:v2.0.10k
          imagePullPolicy: Always #每次启动都重新拉取镜像
          ports:
            - containerPort: 10200
          volumeMounts:
            - name: config
              mountPath: /Open-IM-Server/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
  strategy: #更新策略
    type: RollingUpdate # 滚动更新

