---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo # 选择这个指定标签执行
  replicas: 1 # 运行pod数量
  template:
    metadata:
      labels:
        app: demo # 标签
    spec:
      containers:
      - name: demo
        image: openim/demo:v2.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 10004
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: openim-config
  strategy: #更新策略
    type: RollingUpdate # 滚动更新
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  ports:
    - name: demo
      protocol: TCP
      port: 10004
      targetPort: 10004
  selector:
    app: demo    
  type: NodePort   