name: "OpenIM CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

env:
  # Define Open-IM-Server variables here
  OPEN_IM_SERVER_ORGANIZATION: openim-sigs
  OPEN_IM_SERVER_REPOSITORY: cla
  OPEN_IM_SERVER_CLA_DOCUMENT: https://github.com/openim-sigs/cla/blob/main/README.md
  OPEN_IM_SERVER_SIGNATURES_PATH: signatures/cla/cla.json
  OPEN_IM_SERVER_ALLOWLIST: kubbot,bot*
  OPEN_IM_SERVER_REMOTE_ORGANIZATION: openim-sigs

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == '/recheck' || github.event.comment.body == '/cla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.REDBOT_GITHUB_TOKEN }}
        with:
          path-to-signatures: ${{ env.OPEN_IM_SERVER_SIGNATURES_PATH }}
          path-to-document: ${{ env.OPEN_IM_SERVER_CLA_DOCUMENT }}
          branch: 'main'
          allowlist: ${{ env.OPEN_IM_SERVER_ALLOWLIST }}

          remote-organization-name: ${{ env.OPEN_IM_SERVER_REMOTE_ORGANIZATION }}
          create-file-commit-message: 'Docs: Creating file for storing ${{ env.OPEN_IM_SERVER_ORGANIZATION }} CLA Signatures'
          custom-notsigned-prcomment: 'ðŸ’• Thank you for your contribution and please kindly read and sign our ${{ env.OPEN_IM_SERVER_CLA_DOCUMENT }}'
          custom-pr-sign-comment: 'The signature to be committed in order to sign ${{ env.OPEN_IM_SERVER_ORGANIZATION }} the CLA'
          custom-allsigned-prcomment: '**ðŸ¤– All Contributors have signed the ${{ env.OPEN_IM_SERVER_ORGANIZATION }} [CLA](https://github.com/openim-sigs/cla/blob/main/README.md).'
        #   lock-pullrequest-aftermerge: false - if you don't want this bot to automatically lock the pull request after merging (default - true)
        #   use-dco-flag: true - If you are using DCO instead of CLA
