name: Github Rebot for Link check error

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'
      - '.lycheeignore'
  push:
    branches: [ main ]
  
  schedule: 
    - cron:  '0 11 * * *'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.7.0
        with:
            # For parameter description, see https://github.com/lycheeverse/lychee#commandline-parameters
            # Actions Link address -> https://github.com/lycheeverse/lychee-action
            # -E, --exclude-all-private    Exclude all private IPs from checking.
            # -i, --insecure               Proceed for server connections considered insecure (invalid TLS)
            # -n, --no-progress            Do not show progress bar.
            # -t, --timeout <timeout>      Website timeout in seconds from connect to response finished [default:20]
            # --max-concurrency <max-concurrency>    Maximum number of concurrent network requests [default: 128]
            # -a --accept <accept>                      Comma-separated list of accepted status codes for valid links
            # docs/.vitepress/dist the site directory to check
            # ./*.md all markdown files in the root directory
          args: --verbose  -E -i --no-progress --exclude-path './CHANGELOG' './**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GH_PAT}}

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Bug reports for links in OpenIM docs
          content-filepath: ./lychee/out.md
          labels: kind/documentation, triage/unresolved, report
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
