# Copyright Â© 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

# https://github.com/BetaHuhn/repo-file-sync-action
name: Synchronize OpenIM Release Branch Public Code To Other Repositories
on:
    push:
        paths:
            - scripts/*
            - docs/*
            - config/*
        branches:
          - release-v*.*
    workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_INSTALLATION_TOKEN: "${{ secrets.BOT_GITHUB_TOKEN }}"
          CONFIG_PATH: .github/sync-release.yml
          ORIGINAL_MESSAGE: true
          SKIP_PR: true
          COMMIT_EACH_FILE: false
          COMMIT_BODY: "ðŸ¤– kubbot to synchronize the warehouse"
          GIT_EMAIL: "3293172751ysy@gmail.com"
          GIT_USERNAME: "kubbot"
          PR_BODY: ðŸ‘Œ kubecub provides automated community services
          REVIEWERS: |
            kubbot
            cubxxw
          PR_LABELS: |
            file-sync
            automerge
          ASSIGNEES: |
            kubbot
        continue-on-error: true